### ISSUE TITLE
How to adapt midi Keyboard to Tulipcc ?

### ISSUE THREAD

**Issue by roman65536** [shorepine/tulipcc#377]
Hi,

Is there an description (or hints) how to adapt Tulip to a particular Midi Keyboard (Slider,Knobs,Button) ??
I use AKAI Professional MPK mini Plus (which doesn't have any Slider) and what I miss a bit is, what is the best way to adapt either the Keyboard or Tulip. 
Should I change the Midi codes sending from Keyboard or should I change Codes in the source code ?

Also which index is doing what  on the IDS (below) ? Is there description (doc or so) ? 
I would like to have adsr values on the knobs or filter settings, how to achieve this ?

I found this in midi.py :

```
# Wire up MIDI controls
# Oxygen49 slider IDs, starting from left.
#SLIDER_IDS = [0x49, 0x4b, 0x48, 0x4a, 0x4f, 0x54, 0x5b, 0x5d, 0x7]
SLIDER_IDS = [74, 71, 91, 93, 73, 72, 5, 84, 7]
# Oxygen49 knobs, top row then second row.
#KNOB_IDS = [0x10, 0x11, 0x12, 0x0a, 0x13, 0x50, 0x51, 0x14]
KNOB_IDS = [75, 76, 92, 95, 10, 77, 78, 79]
# Oxygen49 buttons.  They toggle between 0 and 0x7f.
#BUTTON_IDS = [0x18, 0x19, 0x1a, 0x1b, 0x2c, 0x2d, 0x2e, 0x2f, 0x30,
#              0x71, 0x72, 0x73, 0x74, 0x75, 0x76]
# I had to program these.  See Oxygen49-UserGuide-v1.3.pdf + notes.
BUTTON_IDS = [96, 97, 98, 99, 100, 101, 102, 103, 104,   113, 114, 115, 116, 117, 118]


```

rgds
Roman

**Comment by dpwe** [comment]
Hi Roman - 

I'm sorry this is so obscure, we haven't been able to put a lot of thought into this.

You can use [`run('learn_midi_codes')`](https://github.com/shorepine/tulipcc/blob/main/tulip/shared/py/learn_midi_codes.py) to set the lists of sliders, knobs, and buttons by directly moving them on your connected keyboard.  So there's no need to alter the settings on your controller.

The mapping from individual controls to specific operations is a bit messy.  For the Juno controls, the mappings are set up in [line 543ff of `juno6.py`](https://github.com/shorepine/tulipcc/blob/main/tulip/shared/py/juno6.py#L543), using statements like `midi.KNOB_IDS[0]: 'lfo_rate'` - you can see the available control mappings from that list.

The arpeggiator controls are set up at [line 574 of `midi.py`](https://github.com/shorepine/tulipcc/blob/main/tulip/shared/py/midi.py#L574).

Looking at the code will at least help you understand which control will be mapped to each control.  However, if you want to change it (for instance to use knobs instead of sliders), you'll need to edit the code at present.  Although these are Python files, they are frozen into the app, so AFAIU you can't edit them on the Tulip itself.  We'd love to improve this.
